# Generated by Django 4.2.7 on 2023-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drive_wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Engine_conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ManyToManyField(to='guessing.car_type'),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_wheel',
            field=models.ManyToManyField(to='guessing.drive_wheel'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_conf',
            field=models.ManyToManyField(to='guessing.engine_conf'),
        ),
    ]
