# Generated by Django 4.2.7 on 2024-01-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guessing', '0002_car_type_drive_wheel_engine_conf_car_car_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='car_pics')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guessing.picture'),
        ),
    ]
