# Generated by Django 4.2.7 on 2024-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessing', '0003_picture_car_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='car_pics'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
