# Generated by Django 4.2.7 on 2024-06-02 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guessing', '0006_brand_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
